_welcome:
    path:     /
    defaults: { _controller: AcmeDemoBundle:Welcome:index }

_demo_secured:
    resource: "@AcmeDemoBundle/Controller/SecuredController.php"
    type:     annotation

_demo:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo


#added
_random:
    #resource: "@AcmeDemoBundle/Controller/RandomController.php"
    #type:     annotation

    prefix:   /random
    path: /random/{limit}
    defaults: { _controller: AcmeDemoBundle:Random:index }

#trying to call some other method
#_random:
    #resource: "@AcmeDemoBundle/Controller/RandomController.php"
    #type:     annotation

    #prefix:   /random

index:
    path:     /index
    defaults: { _controller: AcmeDemoBundle:Main:index }

other:
    path:     /other
    defaults: { _controller: AcmeDemoBundle:Main:other }